#ansible-playbook user.yaml --extra-vars "user=user_name uid=666 group=group_name"
#ansible user模块：创建用户|创建用户组

- name: "create user"
- hosts: localhost
  tasks:
    - name: create deploy user
      user:
        name: "{{ user }}" #定义对象
        uid: "{{ uid }}"
        append: yes
        group: "{{ group }}"
        state: present
        home: "/tmp/{{ user }}"